User.create(name: '斉藤', age: 35, address: '東京')
User.create(name: '田中', age: 21, address: '愛知')
User.create(name: '佐藤', age: 32, address: '沖縄')
User.create(name: '山岸', age: 33, address: '東京')
User.create(name: '平', age: 26, address: '北海道')
User.create(name: '加藤', age: 25, address: '神戸')
